### PR TITLE
Fix interplay with annotation overlay (fixes #27)

### LINKED ISSUE #27: Don't hide annotations rendered by Mirador itself
Currently we're hiding annotations drawn by Mirador itself when the overlay is set to `visible`. This is because our overlay is positioned after the canvas overlay drawing the annotations, thus occluding it when we render the line boxes and text.

This is not easy to solve, since a hard requirement for us is that the text must be both selectable and visible. If we just positioned our overlay before the canvas overlay, our text would be visible, but no longer selectable.

A solution could be access the annotation state and render them ourselves into our SVG. However, this would incur a lot of future work, since we'd essentially have to replicate any and all modifications to the annotation rendering (which is done on a `canvas` in M3 itself) to our SVG-rendering.

A "good enough" solution would be to restrict ourselves to just rendering *search* annotations. These are just rectangles and could easily be added to the SVG.

### PR DESCRIPTION
**Pull request by jbaiter**
This is achieved by a brutal hack (see docstring on `patchAnnotationOverlay`), but it works for:

- rendering search annotations
- rendering regular annotations
- editing annotations with the `mirador-annotations` plugin

To try it out, search for something in the "Wunder der Vererbung" manifest.

### CODE REVIEW

File: src/components/MiradorTextOverlay.js [hunk 1]
```diff
@@ -165,6 +168,49 @@ class MiradorTextOverlay extends Component {
     viewer.addHandler('update-viewport', this.onUpdateViewport.bind(this));
   }
 
+  /**
+   * Patch the neighboring AnnotatinOverlay container to work with the text overlay.
```
Comment (stefan-it) [inline src/components/MiradorTextOverlay.js:172]:
```suggestion
   * Patch the neighboring AnnotationOverlay container to work with the text overlay.
```
